var Case1_HUB = (function(self){
self.ID = {"text":"Case1_HUB"};
self.preload = {"images":
[	{"url":"bg-case-1.jpg"},
	{"url":"bg4.jpg"},
	{"url":"intro2.jpg"},
	{"url":"1.2.1_macrostatistik.png"},
	{"url":"1.2.2_microstatistik.png"},
	{"url":"1.1.2_bordell.png"},
	{"url":"1.4.2_bild1.png"},
	{"url":"1.4.2_bild2.png"},
	{"url":"1.4.2_bild3.png"},
	{"url":"1.4.2_bild4.png"},
	{"url":"1.4.2_bild5.png"},
	{"url":"1.4.1_blogg2.png"}, 
	{"url":"1.5.1_domen.png"},
	{"url":"1.3.1_insandare.png"},
	{"url":"1.5.2_horan1.png"},
	{"url":"1.5.2_torsken1.png"},
	{"url":"1.5.2_hallicken1.png"},
	{"url":"1.5.2_horan2.png"},
	{"url":"1.5.2_torsken2.png"},
	{"url":"1.5.2_hallicken2.png"},
	{"url":"1.5.2_horan3.png"},
	{"url":"1.5.2_torsken3.png"},
	{"url":"1.5.2_hallicken3.png"},
	{"url":"1.5.2_horan4.png"},
	{"url":"1.5.2_torsken4.png"},
	{"url":"1.5.2_hallicken4.png"},
	{"url":"1.5.2_horan5.png"},
	{"url":"1.5.2_torsken5.png"},
	{"url":"1.5.2_hallicken5.png"},
	{"url":"1.5.2_horan6.png"},
	{"url":"1.5.2_torsken6.png"},
	{"url":"1.5.2_hallicken6.png"},
	{"url":"1.5.2_horan7.png"},
	{"url":"1.5.2_torsken7.png"},
	{"url":"1.5.2_hallicken7.png"},
	{"url":"1.5.2_horan8.png"},
	{"url":"1.5.2_torsken8.png"},
	{"url":"1.5.2_hallicken8.png"}
]
};

self.topLeftImage = {"url":""};

self.nodes = {"content": 
	[{  "ID": "CASE1.HUB",
		"type":"hub", 
		"analysisLog":"CASE 1 HUB:",
		"background":{"type":"image","url":"bg-case-1.jpg"},
		"chapters":[
							{"text":"Vad är trafficking?", 
								"ID":"0",
								"lockeduntil":"0", 
								"width":"220px", "height":"138px", 
								"left":"45%", "top":"34%", 
								"paddingtop":"13px",
								"fontsize":"2.2",
								"analysisLog":"1. Vad är trafficking",
								"callback":"Case1_trafficking"},
							{"text":"Vem köper sex?", 
								"ID":"1",								
								"lockeduntil":"0", 
								"width":"160px", "height":"130px", 
								"left":"82%", "top":"48%", 
								"paddingtop":"20px",
								"fontsize":"2",
								"analysisLog":"3. Vem köper sex",
								"callback":"Case1_sexkopare"},
							{"text":"Människorna som säljs", 
								"ID":"2",
								"lockeduntil":"0", 
								"width":"179px", "height":"117px", 
								"left":"43%", "top":"61%",
								"paddingtop":"13px", 
								"fontsize":"1.8",
								"analysisLog":"4. Människorna som säljs",
								"callback":"Case1_manniskorna"},
							{"text":"Vad gör polisen?", 
								"ID":"3",
								"lockeduntil":"0", 
								"width":"221px", "height":"82px", 
								"left":"68%", "top":"71%",
								"paddingtop":"13px", 
								"fontsize":"2",
								"analysisLog":"5. Vad gör polisen?",
								"callback":"Case1_polisen"},
							{"text":"I lägenheten bredvid", 
								"ID":"4",
								"lockeduntil":"0",
								"width":"240px", "height":"125px", 
								"left":"8%", "top":"14%",
								"paddingtop":"12px", 
								"fontsize":"2",
								"analysisLog":"2. Grannen",
								"callback":"Case1_grannen"},
							{"text":"En vanlig dag", 
								"ID":"5",
								"lockeduntil":"0", 
								"width":"215px", "height":"100px",
								 "left":"10%", "top":"62%", 
								 "paddingtop":"17px",
								 "fontsize":"2.3",
								 "analysisLog":"7. En vanlig dag",
								 "callback":"Case1_envanligdag"},
							{"text":"Vad händer efteråt?", 
								"ID":"6",
								"lockeduntil":"0", 
								"width":"245px", "height":"162px", 
								"left":"72%", "top":"13%", 
								"paddingtop":"13px",
								"fontsize":"2.6",
								"analysisLog":"6. outro case1",
								"callback":"Case1_outro"}
				],
		 "animation":"fade",
		 "showNextButton":"-1"
	}
	

    ]
};


	return self;

})({});
