var Case1_HUB = (function(self){
self.ID = {"text":"Case1_HUB"};
self.preload = {"images":
[	{"url":"bg-case-1.jpg"},
	{"url":"bg4.jpg"},
	{"url":"intro2.jpg"},
	{"url":"1.2.1_macrostatistik.png"},
	{"url":"1.2.2_microstatistik.png"},
	{"url":"1.1.2_bordell.png"},
	{"url":"1.4.2_bild1.png"},
	{"url":"1.4.2_bild2.png"},
	{"url":"1.4.2_bild3.png"},
	{"url":"1.4.2_bild4.png"},
	{"url":"1.4.2_bild5.png"},
	{"url":"1.4.1_blogg2.png"}, 
	{"url":"1.5.1_domen.png"},
	{"url":"1.3.1_insandare.png"},
	{"url":"1.5.2_horan1.png"},
	{"url":"1.5.2_torsken1.png"},
	{"url":"1.5.2_hallicken1.png"},
	{"url":"1.5.2_horan2.png"},
	{"url":"1.5.2_torsken2.png"},
	{"url":"1.5.2_hallicken2.png"},
	{"url":"1.5.2_horan3.png"},
	{"url":"1.5.2_torsken3.png"},
	{"url":"1.5.2_hallicken3.png"},
	{"url":"1.5.2_horan4.png"},
	{"url":"1.5.2_torsken4.png"},
	{"url":"1.5.2_hallicken4.png"},
	{"url":"1.5.2_horan5.png"},
	{"url":"1.5.2_torsken5.png"},
	{"url":"1.5.2_hallicken5.png"},
	{"url":"1.5.2_horan6.png"},
	{"url":"1.5.2_torsken6.png"},
	{"url":"1.5.2_hallicken6.png"},
	{"url":"1.5.2_horan7.png"},
	{"url":"1.5.2_torsken7.png"},
	{"url":"1.5.2_hallicken7.png"},
	{"url":"1.5.2_horan8.png"},
	{"url":"1.5.2_torsken8.png"},
	{"url":"1.5.2_hallicken8.png"}
]
};

self.topLeftImage = {"url":""};

self.nodes = {"content": 
	[{  "ID": "CASE1.HUB",
		"type":"hub", 
		"analysisLog":"CASE 1 HUB:",
		"background":{"type":"image","url":"bg-case-1.jpg"},
		"chapters":[
							{"text":"Vad är trafficking?", 
								"ID":"0",
								"lockeduntil":"1", 
								"width":"322px", "height":"49px", 
								"left":"45%", "top":"34%", 
								"paddingtop":"10px",
								"fontsize":"2",
								"analysisLog":"1. Vad är trafficking",
								"callback":"Case1_trafficking"},
							{"text":"Vem köper sex?", 
								"ID":"1",								
								"lockeduntil":"1", 
								"width":"121px", "height":"132px", 
								"left":"79%", "top":"45%", 
								"paddingtop":"10px",
								"fontsize":"2.2",
								"analysisLog":"3. Vem köper sex",
								"callback":"Case1_sexkopare"},
							{"text":"Människorna som säljs", 
								"ID":"2",
								"lockeduntil":"0", 
								"width":"365px", "height":"49px", 
								"left":"30%", "top":"65%",
								"paddingtop":"10px", 
								"fontsize":"2",
								"analysisLog":"4. Människorna som säljs",
								"callback":"Case1_manniskorna"},
							{"text":"Vad gör polisen?", 
								"ID":"3",
								"lockeduntil":"3", 
								"width":"277px", "height":"49px", 
								"left":"72%", "top":"71%",
								"paddingtop":"10px", 
								"fontsize":"2",
								"analysisLog":"5. Vad gör polisen?",
								"callback":"Case1_polisen"},
							{"text":"I lägenheten bredvid", 
								"ID":"4",
								"lockeduntil":"2",
								"width":"348px", "height":"49px", 
								"left":"1%", "top":"18%",
								"paddingtop":"10px", 
								"fontsize":"2",
								"analysisLog":"2. Grannen",
								"callback":"Case1_grannen"},
							{"text":"En vanlig dag", 
								"ID":"5",
								"lockeduntil":"4", 
								"width":"239px", "height":"49px",
								 "left":"-2%", "top":"41%", 
								 "paddingtop":"10px",
								 "fontsize":"2",
								 "analysisLog":"7. En vanlig dag",
								 "callback":"Case1_envanligdag"},
							{"text":"Vad händer efteråt?", 
								"ID":"6",
								"lockeduntil":"6", 
								"width":"172px", "height":"139px", 
								"left":"82%", "top":"16%", 
								"paddingtop":"10px",
								"fontsize":"2.4",
								"analysisLog":"6. outro case1",
								"callback":"Case1_outro"}
				],
		 "animation":"fade",
		 "showNextButton":"-1"
	}
	

    ]
};


	return self;

})({});
